# This file was generated by the {rix} R package v0.18.2 on 2026-05-28
# with following call:
# >rix(date = "2026-05-25",
#  > r_pkgs = c("modsem",
#  > "covsim",
#  > "rvinecopulib",
#  > "ggplot2"),
#  > git_pkgs = list(package_name = "lavaan",
#  > repo_url = "https://github.com/yrosseel/lavaan",
#  > commit = "52d303c"),
#  > project_path = ".",
#  > overwrite = TRUE,
#  > r_ver = "4.6.0")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-05-25.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      covsim
      ggplot2
      modsem
      rvinecopulib;
  };
 
    lavaan = (pkgs.rPackages.buildRPackage {
      name = "lavaan";
      src = pkgs.fetchgit {
        url = "https://github.com/yrosseel/lavaan";
        rev = "52d303c";
        sha256 = "sha256-d3GnS04p2hDBAttKeb02yGM5vyj68qKLoB1p16NJWfM=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          MASS
          mnormt
          pbivnorm
          numDeriv
          quadprog;
      };
    });
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ lavaan rpkgs system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
