# This file was generated by the {rix} R package v0.18.2 on 2026-06-10
# with following call:
# >rix(date = "2026-05-11",
#  > r_pkgs = c("covsim",
#  > "rvinecopulib",
#  > "knitr"),
#  > system_pkgs = "quarto",
#  > git_pkgs = list(list(package_name = "lavaan",
#  > repo_url = "https://github.com/yrosseel/lavaan",
#  > commit = "8d99872"),
#  > list(package_name = "modsem",
#  > repo_url = "https://github.com/felipelfv/modsem",
#  > commit = "b189bfec2a743ccfcca4c197127861d17ba88fd3")),
#  > tex_pkgs = c("amsmath",
#  > "framed",
#  > "fvextra",
#  > "fancyvrb",
#  > "booktabs",
#  > "caption",
#  > "etoolbox",
#  > "xcolor",
#  > "geometry",
#  > "hyperref",
#  > "float"),
#  > project_path = ".",
#  >      overwrite = TRUE,
#  > r_ver = "4.6.0")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-05-11.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      covsim
      knitr
      rvinecopulib;
  };
 
    lavaan = (pkgs.rPackages.buildRPackage {
      name = "lavaan";
      src = pkgs.fetchgit {
        url = "https://github.com/yrosseel/lavaan";
        rev = "8d99872";
        sha256 = "sha256-HeDHqg0rU/75S2zlOToBViOTvfC7ED5npicIxIKsqCk=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          MASS
          mnormt
          pbivnorm
          numDeriv
          quadprog;
      };
    });

    modsem = (pkgs.rPackages.buildRPackage {
      name = "modsem";
      src = pkgs.fetchgit {
        url = "https://github.com/felipelfv/modsem";
        rev = "b189bfec2a743ccfcca4c197127861d17ba88fd3";
        sha256 = "sha256-CTXW3te447eE+m/zaCi3728LRiAls6S+vlzmybaJsA0=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          Rcpp
          purrr
          stringr
          lavaan
          rlang
          nlme
          dplyr
          mvnfast
          fastGHQuad
          mvtnorm
          ggplot2
          plotly
          Deriv
          MASS
          Amelia
          cli
          RhpcBLASctl
          memoise
          RcppArmadillo;
      };
    });
  
  tex = (pkgs.texlive.combine {
    inherit (pkgs.texlive) 
      scheme-small
      amsmath
      booktabs
      caption
      etoolbox
      fancyvrb
      float
      framed
      fvextra
      geometry
      hyperref
      xcolor;
  });
    
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      quarto;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ lavaan modsem rpkgs tex system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
