# This file was generated by the {rix} R package v0.18.2 on 2026-09-03
# with following call:
# >rix(date = "2026-05-11",
#  > r_pkgs = c("covsim",
#  > "rvinecopulib",
#  > "tidyr",
#  > "ggplot2",
#  > "simhelpers",
#  > "dplyr",
#  > "knitr"),
#  > system_pkgs = "quarto",
#  > git_pkgs = list(list(package_name = "lavaan",
#  > repo_url = "https://github.com/yrosseel/lavaan",
#  > commit = "34f69c74f0f65067c7d01f75be4b9f67b8493aff"),
#  > list(package_name = "modsem",
#  > repo_url = "https://github.com/Kss2k/modsem",
#  > commit = "5c365472e7ffd2796654c77530e5c305946a3e80")),
#  > tex_pkgs = c("amsmath",
#  > "framed",
#  > "fvextra",
#  > "fancyvrb",
#  > "booktabs",
#  > "caption",
#  > "etoolbox",
#  >      "xcolor",
#  > "geometry",
#  > "hyperref",
#  > "float",
#  > "pgf",
#  > "standalone",
#  > "apa7",
#  > "scalerel",
#  > "endfloat",
#  > "substr",
#  > "xstring",
#  > "threeparttable",
#  > "threeparttablex",
#  > "multirow",
#  > "colortbl",
#  > "xpatch",
#  > "lineno",
#  > "fontawesome5",
#  > "newtx",
#  > "fontaxes",
#  > "pbalance",
#  > "tcolorbox",
#  > "tikzfill",
#  > "environ",
#  > "pdfcol",
#  > "mathspec",
#  > "xecjk",
#  > "pdflscape",
#  > "babel-english"),
#  > project_path = ".",
#  > overwrite = TRUE,
#  > r_ver = "4.6.0")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-05-11.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      covsim
      dplyr
      ggplot2
      knitr
      rvinecopulib
      simhelpers
      tidyr;
  };
 
    lavaan = (pkgs.rPackages.buildRPackage {
      name = "lavaan";
      src = pkgs.fetchgit {
        url = "https://github.com/yrosseel/lavaan";
        rev = "34f69c74f0f65067c7d01f75be4b9f67b8493aff";
        sha256 = "sha256-z2LjjN75z50lu9K30yBcZsHQp38TiX1ynMZwca9lvLM=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          MASS
          mnormt
          pbivnorm
          numDeriv
          quadprog;
      };
    });

    modsem = (pkgs.rPackages.buildRPackage {
      name = "modsem";
      src = pkgs.fetchgit {
        url = "https://github.com/Kss2k/modsem";
        rev = "5c365472e7ffd2796654c77530e5c305946a3e80";
        sha256 = "sha256-x653JkCKgDb/H6UGAG+V9yVkeLusCPgYBkEvu8qBdY4=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          Rcpp
          purrr
          stringr
          lavaan
          rlang
          nlme
          dplyr
          mvnfast
          fastGHQuad
          mvtnorm
          ggplot2
          plotly
          Deriv
          MASS
          Amelia
          cli
          RhpcBLASctl
          memoise
          RcppArmadillo;
      };
    });
  
  tex = (pkgs.texlive.combine {
    inherit (pkgs.texlive) 
      scheme-small
      amsmath
      apa7
      babel-english
      booktabs
      caption
      colortbl
      endfloat
      environ
      etoolbox
      fancyvrb
      float
      fontawesome5
      fontaxes
      framed
      fvextra
      geometry
      hyperref
      lineno
      mathspec
      multirow
      newtx
      pbalance
      pdfcol
      pdflscape
      pgf
      scalerel
      standalone
      substr
      tcolorbox
      threeparttable
      threeparttablex
      tikzfill
      xcolor
      xecjk
      xpatch
      xstring;
  });
    
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      quarto
      R;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ lavaan modsem rpkgs tex system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
